export const API_ROUTES = {
  REGISTER: '/api/register',
  LOGIN: '/api/login',
  USER: '/api/user',
  FINDUSER: '/api/finduser',
  PROFILE: '/api/profile',
  LOGOUT: '/api/logout',
  PRODUCT_ADD: '/api/addProducts',
  PRODUCT_LIST: '/api/products',
  OPTIONS_LIST: '/options/list',
  OPTIONS_ADD: '/options/add',
  OPTIONS_UPDATE: '/options/edit/${id}',
  OPTIONS_DISABLE: '/options/disable/${id}',
  OPTIONS_BY_LISTNAME: '/options/getByListName',
  PRODUCT_DETAIL: (id) => `/api/products/edit/${id}`,
  PRODUCT_UPDATE: (id) => `/api/updateProducts/${id}`,
  PRODUCT_DELETE: (id) => `/api/deleteProducts/${id}`,
}
